### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Perfare** [mafaca/Atc#1]
https://github.com/mafaca/Atc/blob/005a4d6e2d076fb1991f9b646184fe795f680710/Atc/AtcDecoder.cs#L113-L119
ATC lerp factors are 3/8 and 5/8, not 1/3 and 2/3.
Referer https://github.com/BinomialLLC/basis_universal/blob/fadb1e8e940656f100d0112bcfe6146854b1b468/basisu_gpu_texture.cpp#L242

https://github.com/mafaca/Atc/blob/005a4d6e2d076fb1991f9b646184fe795f680710/Atc/AtcDecoder.cs#L135-L137
Here will get a negative value, it should be compared with 0.

The atc alpha channel uses the bc3/dxt5 alpha channel encoding code, and bc4, bc5 are also used bc3/dxt5 alpha channel encoding code, can consider putting them together.

**Comment by mafaca** [comment]
Thanks. Fixed that.

> The atc alpha channel uses the bc3/dxt5 alpha channel encoding code

Yes, I know that, but i want to separate different types of converters and make them independent from each other.
